// Code generated by server/cmd/protocolgen; DO NOT EDIT.

export const PROTOCOL_EVENT = {
  SYSTEM_INIT: 'system/init',
  SYSTEM_ADMIN: 'system/admin',
  SYSTEM_SETTINGS: 'system/settings',
  SYSTEM_LOGS: 'system/logs',
  SYSTEM_DISCONNECT: 'system/disconnect',
  SYSTEM_HEARTBEAT: 'system/heartbeat',
  SYSTEM_ERROR: 'system/error',
  CLIENT_HEARTBEAT: 'client/heartbeat',
  SIGNAL_REQUEST: 'signal/request',
  SIGNAL_RESTART: 'signal/restart',
  SIGNAL_OFFER: 'signal/offer',
  SIGNAL_ANSWER: 'signal/answer',
  SIGNAL_PROVIDE: 'signal/provide',
  SIGNAL_CANDIDATE: 'signal/candidate',
  SIGNAL_CLOSE: 'signal/close',
  SIGNAL_VIDEO: 'signal/video',
  SIGNAL_AUDIO: 'signal/audio',
  SESSION_CREATED: 'session/created',
  SESSION_DELETED: 'session/deleted',
  SESSION_PROFILE: 'session/profile',
  SESSION_STATE: 'session/state',
  SESSION_CURSORS: 'session/cursors',
  CONTROL_HOST: 'control/host',
  CONTROL_RELEASE: 'control/release',
  CONTROL_REQUEST: 'control/request',
  CONTROL_RENEW: 'control/renew',
  SCREEN_UPDATED: 'screen/updated',
  SCREEN_SET: 'screen/set',
  CLIPBOARD_UPDATED: 'clipboard/updated',
  CLIPBOARD_SET: 'clipboard/set',
  KEYBOARD_MODIFIERS: 'keyboard/modifiers',
  KEYBOARD_MAP: 'keyboard/map',
  SEND_UNICAST: 'send/unicast',
  SEND_BROADCAST: 'send/broadcast',
  FILE_CHOOSER_DIALOG_OPENED: 'file_chooser_dialog/opened',
  FILE_CHOOSER_DIALOG_CLOSED: 'file_chooser_dialog/closed',
  CHAT_INIT: 'chat/init',
  CHAT_MESSAGE: 'chat/message',
  CHAT_EMOTE: 'chat/emote',
  FILETRANSFER_UPDATE: 'filetransfer/update',
  OPENINAPP_INIT: 'openinapp/init',
  OPENINAPP_OPENLINK: 'openinapp/openlink',
} as const

export type ProtocolEvent = (typeof PROTOCOL_EVENT)[keyof typeof PROTOCOL_EVENT]

export const PROTOCOL_ERROR = {
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  UNKNOWN_EVENT: 'UNKNOWN_EVENT',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ROOM_NOT_READY: 'ROOM_NOT_READY',
  CONTROL_CONFLICT: 'CONTROL_CONFLICT',
  STALE_EPOCH: 'STALE_EPOCH',
  ICE_FAILED: 'ICE_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ProtocolErrorCode = (typeof PROTOCOL_ERROR)[keyof typeof PROTOCOL_ERROR]

export const RETRYABLE_PROTOCOL_ERRORS: ReadonlySet<ProtocolErrorCode> = new Set([
  PROTOCOL_ERROR.ROOM_NOT_READY,
  PROTOCOL_ERROR.CONTROL_CONFLICT,
  PROTOCOL_ERROR.ICE_FAILED,
  PROTOCOL_ERROR.INTERNAL_ERROR,
])
