// Code generated by server/cmd/protocolgen; DO NOT EDIT.

export interface BroadcastStatusPayload {
  is_active: boolean
  url?: string
}

export interface ChatContentPayload {
  text: string
}

export interface ChatEmotePayload {
  emote: string
  id: string
}

export interface ChatHistoryMessagePayload {
  avatar?: string
  content: ChatContentPayload
  created: string
  id: string
  name?: string
}

export interface ChatInitPayload {
  enabled: boolean
  history?: Array<ChatHistoryMessagePayload>
}

export interface ChatMessagePayload {
  avatar?: string
  content?: ChatContentPayload
  created?: string
  id?: string
  name?: string
  text?: string
}

export interface ClipboardDataPayload {
  text: string
}

export interface ControlEpochPayload {
  epoch: number
}

export interface ControlHostPayload {
  epoch: number
  has_host: boolean
  host_id?: string
  id: string
}

export interface CursorPayload {
  x: number
  y: number
}

export interface ErrorPayload {
  code: string
  message: string
  retryable: boolean
  title: string
}

export interface FileTransferItemPayload {
  name: string
  size?: number
  type: string
}

export interface FileTransferUpdatePayload {
  enabled: boolean
  files: Array<FileTransferItemPayload>
  root_dir: string
  user_delete: boolean
  user_download: boolean
  user_upload: boolean
}

export interface ICEServerPayload {
  credential?: string
  urls: Array<string>
  username?: string
}

export interface KeyboardMapPayload {
  layout: string
  variant: string
}

export interface KeyboardModifiersPayload {
  alt?: boolean
  altgr?: boolean
  capslock?: boolean
  control?: boolean
  meta?: boolean
  numlock?: boolean
  shift?: boolean
  super?: boolean
}

export interface MemberProfilePayload {
  avatar?: string
  can_access_clipboard: boolean
  can_connect: boolean
  can_host: boolean
  can_login: boolean
  can_see_inactive_cursors: boolean
  can_share_media: boolean
  can_watch: boolean
  is_admin: boolean
  name: string
  plugins: Record<string, unknown> | null
  sends_inactive_cursor: boolean
}

export interface OpenInAppInitPayload {
  enabled: boolean
}

export interface OpenInAppLinkPayload {
  text: string
}

export interface PeerAudioPayload {
  disabled: boolean
}

export interface PeerAudioRequestPayload {
  disabled?: boolean
}

export interface PeerVideoPayload {
  auto: boolean
  disabled: boolean
  id: string
}

export interface PeerVideoRequestPayload {
  auto?: boolean
  disabled?: boolean
  selector?: StreamSelectorPayload
}

export interface ScreenSizePayload {
  height: number
  rate: number
  width: number
}

export interface ScreenSizeUpdatePayload {
  height: number
  id: string
  rate: number
  width: number
}

export interface SendBroadcastPayload {
  body: unknown
  sender: string
  subject: string
}

export interface SendUnicastPayload {
  body: unknown
  receiver: string
  sender: string
  subject: string
}

export interface SessionCursorsPayload {
  cursors: Array<CursorPayload>
  id: string
}

export interface SessionDataPayload {
  id: string
  profile: MemberProfilePayload
  state: SessionStatePayload
}

export interface SessionIDPayload {
  id: string
}

export interface SessionProfileUpdatePayload {
  avatar?: string
  can_access_clipboard: boolean
  can_connect: boolean
  can_host: boolean
  can_login: boolean
  can_see_inactive_cursors: boolean
  can_share_media: boolean
  can_watch: boolean
  id: string
  is_admin: boolean
  name: string
  plugins: Record<string, unknown> | null
  sends_inactive_cursor: boolean
}

export interface SessionStatePayload {
  connected_since?: string | null
  is_connected: boolean
  is_watching: boolean
  not_connected_since?: string | null
  not_watching_since?: string | null
  watching_since?: string | null
}

export interface SessionStateUpdatePayload {
  connected_since?: string | null
  id: string
  is_connected: boolean
  is_watching: boolean
  not_connected_since?: string | null
  not_watching_since?: string | null
  watching_since?: string | null
}

export interface SettingsPayload {
  control_lease_ttl: number
  control_protection: boolean
  heartbeat_interval: number
  implicit_hosting: boolean
  inactive_cursors: boolean
  locked_controls: boolean
  locked_logins: boolean
  merciful_reconnect: boolean
  plugins: Record<string, unknown> | null
  private_mode: boolean
}

export interface SignalCandidatePayload {
  candidate: string
  sdpMLineIndex?: number | null
  sdpMid?: string | null
  usernameFragment?: string | null
}

export interface SignalDescriptionPayload {
  sdp: string
}

export interface SignalProvidePayload {
  audio: PeerAudioPayload
  iceservers: Array<ICEServerPayload>
  sdp: string
  video: PeerVideoPayload
}

export interface SignalRequestPayload {
  audio?: PeerAudioRequestPayload
  video?: PeerVideoRequestPayload
  video_codecs?: Array<string>
}

export interface StreamSelectorPayload {
  bitrate: number
  id: string
  type: string
}

export interface SystemAdminPayload {
  broadcast_status: BroadcastStatusPayload
}

export interface SystemDisconnectPayload {
  message: string
}

export interface SystemInitPayload {
  control_host: ControlHostPayload
  screen_size: ScreenSizePayload
  screencast_enabled: boolean
  session_id: string
  sessions: Record<string, SessionDataPayload>
  settings: SettingsPayload
  touch_events: boolean
  webrtc: SystemWebRTCPayload
}

export interface SystemLogPayload {
  fields: Record<string, unknown>
  level: string
  message: string
}

export interface SystemSettingsUpdatePayload {
  control_lease_ttl: number
  control_protection: boolean
  heartbeat_interval: number
  id: string
  implicit_hosting: boolean
  inactive_cursors: boolean
  locked_controls: boolean
  locked_logins: boolean
  merciful_reconnect: boolean
  plugins: Record<string, unknown> | null
  private_mode: boolean
}

export interface SystemWebRTCPayload {
  videos: Array<string>
}
