// Code generated by server/cmd/protocolgen; DO NOT EDIT.

export interface ChatMessagePayload {
  text: string
}

export interface ClipboardDataPayload {
  text: string
}

export interface ControlEpochPayload {
  epoch: number
}

export interface ErrorPayload {
  code: string
  message: string
  retryable: boolean
  title: string
}

export interface KeyboardMapPayload {
  layout: string
  variant?: string
}

export interface KeyboardModifiersPayload {
  alt?: boolean
  altgr?: boolean
  capslock?: boolean
  control?: boolean
  meta?: boolean
  numlock?: boolean
  shift?: boolean
  super?: boolean
}

export interface PeerAudioRequestPayload {
  disabled?: boolean
}

export interface PeerVideoRequestPayload {
  auto?: boolean
  disabled?: boolean
  selector?: Record<string, unknown>
}

export interface ScreenSizePayload {
  height: number
  rate: number
  width: number
}

export interface SignalCandidatePayload {
  candidate: string
  sdpMLineIndex?: number | null
  sdpMid?: string | null
  usernameFragment?: string | null
}

export interface SignalDescriptionPayload {
  sdp: string
}

export interface SignalRequestPayload {
  audio?: PeerAudioRequestPayload
  video?: PeerVideoRequestPayload
  video_codecs?: Array<string>
}
