import { PROTOCOL_EVENT } from '../protocol/events.generated'

export const EVENT = {
  // Internal Events
  RECONNECTING: 'RECONNECTING',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  TRACK: 'TRACK',
  MESSAGE: 'MESSAGE',
  DATA: 'DATA',

  // Websocket Events
  SYSTEM: {
    INIT: PROTOCOL_EVENT.SYSTEM_INIT,
    ADMIN: PROTOCOL_EVENT.SYSTEM_ADMIN,
    SETTINGS: PROTOCOL_EVENT.SYSTEM_SETTINGS,
    HEARTBEAT: PROTOCOL_EVENT.SYSTEM_HEARTBEAT,
    DISCONNECT: PROTOCOL_EVENT.SYSTEM_DISCONNECT,
    ERROR: PROTOCOL_EVENT.SYSTEM_ERROR,
  },
  CLIENT: {
    HEARTBEAT: PROTOCOL_EVENT.CLIENT_HEARTBEAT,
  },
  SIGNAL: {
    REQUEST: PROTOCOL_EVENT.SIGNAL_REQUEST,
    RESTART: PROTOCOL_EVENT.SIGNAL_RESTART,
    OFFER: PROTOCOL_EVENT.SIGNAL_OFFER,
    ANSWER: PROTOCOL_EVENT.SIGNAL_ANSWER,
    PROVIDE: PROTOCOL_EVENT.SIGNAL_PROVIDE,
    CANDIDATE: PROTOCOL_EVENT.SIGNAL_CANDIDATE,
    CLOSE: PROTOCOL_EVENT.SIGNAL_CLOSE,
  },
  SESSION: {
    CREATED: PROTOCOL_EVENT.SESSION_CREATED,
    DELETED: PROTOCOL_EVENT.SESSION_DELETED,
    PROFILE: PROTOCOL_EVENT.SESSION_PROFILE,
    STATE: PROTOCOL_EVENT.SESSION_STATE,
    CURSORS: PROTOCOL_EVENT.SESSION_CURSORS,
  },
  CONTROL: {
    HOST: PROTOCOL_EVENT.CONTROL_HOST,
    RELEASE: PROTOCOL_EVENT.CONTROL_RELEASE,
    REQUEST: PROTOCOL_EVENT.CONTROL_REQUEST,
    RENEW: PROTOCOL_EVENT.CONTROL_RENEW,
  },
  CHAT: {
    INIT: PROTOCOL_EVENT.CHAT_INIT,
    MESSAGE: PROTOCOL_EVENT.CHAT_MESSAGE,
    EMOTE: PROTOCOL_EVENT.CHAT_EMOTE,
  },
  FILETRANSFER: {
    UPDATE: PROTOCOL_EVENT.FILETRANSFER_UPDATE,
  },
  OPENINAPP: {
    INIT: PROTOCOL_EVENT.OPENINAPP_INIT,
    OPENLINK: PROTOCOL_EVENT.OPENINAPP_OPENLINK,
  },
  SCREEN: {
    UPDATED: PROTOCOL_EVENT.SCREEN_UPDATED,
    SET: PROTOCOL_EVENT.SCREEN_SET,
  },
  CLIPBOARD: {
    UPDATED: PROTOCOL_EVENT.CLIPBOARD_UPDATED,
    SET: PROTOCOL_EVENT.CLIPBOARD_SET,
  },
  KEYBOARD: {
    MAP: PROTOCOL_EVENT.KEYBOARD_MAP,
    MODIFIERS: PROTOCOL_EVENT.KEYBOARD_MODIFIERS,
  },
} as const

export type Events = typeof EVENT

export type WebSocketEvents =
  | SystemEvents
  | ClientEvents
  | ControlEvents
  | SessionEvents
  | SignalEvents
  | ChatEvents
  | FileTransferEvents
  | OpenInAppEvents
  | ScreenEvents
  | ClipboardEvents
  | KeyboardEvents

export type ControlEvents =
  | typeof EVENT.CONTROL.HOST
  | typeof EVENT.CONTROL.RELEASE
  | typeof EVENT.CONTROL.REQUEST
  | typeof EVENT.CONTROL.RENEW

export type SystemEvents =
  | typeof EVENT.SYSTEM.INIT
  | typeof EVENT.SYSTEM.ADMIN
  | typeof EVENT.SYSTEM.SETTINGS
  | typeof EVENT.SYSTEM.HEARTBEAT
  | typeof EVENT.SYSTEM.DISCONNECT
  | typeof EVENT.SYSTEM.ERROR
export type ClientEvents = typeof EVENT.CLIENT.HEARTBEAT

export type SessionEvents =
  | typeof EVENT.SESSION.CREATED
  | typeof EVENT.SESSION.DELETED
  | typeof EVENT.SESSION.PROFILE
  | typeof EVENT.SESSION.STATE
  | typeof EVENT.SESSION.CURSORS

export type SignalEvents =
  | typeof EVENT.SIGNAL.REQUEST
  | typeof EVENT.SIGNAL.RESTART
  | typeof EVENT.SIGNAL.OFFER
  | typeof EVENT.SIGNAL.ANSWER
  | typeof EVENT.SIGNAL.PROVIDE
  | typeof EVENT.SIGNAL.CANDIDATE
  | typeof EVENT.SIGNAL.CLOSE

export type ChatEvents = typeof EVENT.CHAT.INIT | typeof EVENT.CHAT.MESSAGE | typeof EVENT.CHAT.EMOTE

export type FileTransferEvents = typeof EVENT.FILETRANSFER.UPDATE

export type OpenInAppEvents = typeof EVENT.OPENINAPP.INIT | typeof EVENT.OPENINAPP.OPENLINK

export type ScreenEvents = typeof EVENT.SCREEN.UPDATED | typeof EVENT.SCREEN.SET

export type ClipboardEvents = typeof EVENT.CLIPBOARD.UPDATED | typeof EVENT.CLIPBOARD.SET

export type KeyboardEvents = typeof EVENT.KEYBOARD.MAP | typeof EVENT.KEYBOARD.MODIFIERS
