// Code generated by cmd/protocolgen; DO NOT EDIT.
package protocol

const (
	SystemInit              = "system/init"
	SystemAdmin             = "system/admin"
	SystemSettings          = "system/settings"
	SystemLogs              = "system/logs"
	SystemDisconnect        = "system/disconnect"
	SystemHeartbeat         = "system/heartbeat"
	SystemError             = "system/error"
	ClientHeartbeat         = "client/heartbeat"
	SignalRequest           = "signal/request"
	SignalRestart           = "signal/restart"
	SignalOffer             = "signal/offer"
	SignalAnswer            = "signal/answer"
	SignalProvide           = "signal/provide"
	SignalCandidate         = "signal/candidate"
	SignalClose             = "signal/close"
	SignalVideo             = "signal/video"
	SignalAudio             = "signal/audio"
	SessionCreated          = "session/created"
	SessionDeleted          = "session/deleted"
	SessionProfile          = "session/profile"
	SessionState            = "session/state"
	SessionCursors          = "session/cursors"
	ControlHost             = "control/host"
	ControlRelease          = "control/release"
	ControlRequest          = "control/request"
	ControlRenew            = "control/renew"
	ScreenUpdated           = "screen/updated"
	ScreenSet               = "screen/set"
	ClipboardUpdated        = "clipboard/updated"
	ClipboardSet            = "clipboard/set"
	KeyboardModifiers       = "keyboard/modifiers"
	KeyboardMap             = "keyboard/map"
	SendUnicast             = "send/unicast"
	SendBroadcast           = "send/broadcast"
	FileChooserDialogOpened = "file_chooser_dialog/opened"
	FileChooserDialogClosed = "file_chooser_dialog/closed"
	ChatInit                = "chat/init"
	ChatMessage             = "chat/message"
	ChatEmote               = "chat/emote"
	FiletransferUpdate      = "filetransfer/update"
	OpeninappInit           = "openinapp/init"
	OpeninappOpenlink       = "openinapp/openlink"
)

var knownEvents = map[string]struct{}{
	SystemInit:              {},
	SystemAdmin:             {},
	SystemSettings:          {},
	SystemLogs:              {},
	SystemDisconnect:        {},
	SystemHeartbeat:         {},
	SystemError:             {},
	ClientHeartbeat:         {},
	SignalRequest:           {},
	SignalRestart:           {},
	SignalOffer:             {},
	SignalAnswer:            {},
	SignalProvide:           {},
	SignalCandidate:         {},
	SignalClose:             {},
	SignalVideo:             {},
	SignalAudio:             {},
	SessionCreated:          {},
	SessionDeleted:          {},
	SessionProfile:          {},
	SessionState:            {},
	SessionCursors:          {},
	ControlHost:             {},
	ControlRelease:          {},
	ControlRequest:          {},
	ControlRenew:            {},
	ScreenUpdated:           {},
	ScreenSet:               {},
	ClipboardUpdated:        {},
	ClipboardSet:            {},
	KeyboardModifiers:       {},
	KeyboardMap:             {},
	SendUnicast:             {},
	SendBroadcast:           {},
	FileChooserDialogOpened: {},
	FileChooserDialogClosed: {},
	ChatInit:                {},
	ChatMessage:             {},
	ChatEmote:               {},
	FiletransferUpdate:      {},
	OpeninappInit:           {},
	OpeninappOpenlink:       {},
}

func IsKnownEvent(event string) bool {
	_, ok := knownEvents[event]
	return ok
}

type ErrorCode string

const (
	InvalidMessage   ErrorCode = "INVALID_MESSAGE"
	UnknownEvent     ErrorCode = "UNKNOWN_EVENT"
	InvalidPayload   ErrorCode = "INVALID_PAYLOAD"
	PermissionDenied ErrorCode = "PERMISSION_DENIED"
	RoomNotReady     ErrorCode = "ROOM_NOT_READY"
	ControlConflict  ErrorCode = "CONTROL_CONFLICT"
	StaleEpoch       ErrorCode = "STALE_EPOCH"
	IceFailed        ErrorCode = "ICE_FAILED"
	NotFound         ErrorCode = "NOT_FOUND"
	InternalError    ErrorCode = "INTERNAL_ERROR"
)

var retryableErrors = map[ErrorCode]bool{
	InvalidMessage:   false,
	UnknownEvent:     false,
	InvalidPayload:   false,
	PermissionDenied: false,
	RoomNotReady:     true,
	ControlConflict:  true,
	StaleEpoch:       false,
	IceFailed:        true,
	NotFound:         false,
	InternalError:    true,
}

func IsRetryable(code ErrorCode) bool {
	return retryableErrors[code]
}
