// Code generated by cmd/protocolgen; DO NOT EDIT.
package protocol

// Protocol payload contracts generated from protocol/payloads.schema.json.
type BroadcastStatusPayload struct {
	IsActive bool    `json:"is_active"`
	Url      *string `json:"url,omitempty"`
}

type ChatContentPayload struct {
	Text string `json:"text"`
}

type ChatEmotePayload struct {
	Emote string `json:"emote"`
	Id    string `json:"id"`
}

type ChatHistoryMessagePayload struct {
	Avatar  *string            `json:"avatar,omitempty"`
	Content ChatContentPayload `json:"content"`
	Created string             `json:"created"`
	Id      string             `json:"id"`
	Name    *string            `json:"name,omitempty"`
}

type ChatInitPayload struct {
	Enabled bool                         `json:"enabled"`
	History *[]ChatHistoryMessagePayload `json:"history,omitempty"`
}

type ChatMessagePayload struct {
	Avatar  *string             `json:"avatar,omitempty"`
	Content *ChatContentPayload `json:"content,omitempty"`
	Created *string             `json:"created,omitempty"`
	Id      *string             `json:"id,omitempty"`
	Name    *string             `json:"name,omitempty"`
	Text    *string             `json:"text,omitempty"`
}

type ClipboardDataPayload struct {
	Text string `json:"text"`
}

type ControlEpochPayload struct {
	Epoch int64 `json:"epoch"`
}

type ControlHostPayload struct {
	Epoch   int64   `json:"epoch"`
	HasHost bool    `json:"has_host"`
	HostId  *string `json:"host_id,omitempty"`
	Id      string  `json:"id"`
}

type CursorPayload struct {
	X int64 `json:"x"`
	Y int64 `json:"y"`
}

type ProtocolErrorPayload struct {
	Code      ErrorCode `json:"code"`
	Message   string    `json:"message"`
	Retryable bool      `json:"retryable"`
	Title     string    `json:"title"`
}

type FileTransferItemPayload struct {
	Name string `json:"name"`
	Size *int64 `json:"size,omitempty"`
	Type string `json:"type"`
}

type FileTransferUpdatePayload struct {
	Enabled      bool                      `json:"enabled"`
	Files        []FileTransferItemPayload `json:"files"`
	RootDir      string                    `json:"root_dir"`
	UserDelete   bool                      `json:"user_delete"`
	UserDownload bool                      `json:"user_download"`
	UserUpload   bool                      `json:"user_upload"`
}

type ICEServerPayload struct {
	Credential *string  `json:"credential,omitempty"`
	Urls       []string `json:"urls"`
	Username   *string  `json:"username,omitempty"`
}

type KeyboardMapPayload struct {
	Layout  string `json:"layout"`
	Variant string `json:"variant"`
}

type KeyboardModifiersPayload struct {
	Alt      *bool `json:"alt,omitempty"`
	Altgr    *bool `json:"altgr,omitempty"`
	Capslock *bool `json:"capslock,omitempty"`
	Control  *bool `json:"control,omitempty"`
	Meta     *bool `json:"meta,omitempty"`
	Numlock  *bool `json:"numlock,omitempty"`
	Shift    *bool `json:"shift,omitempty"`
	Super    *bool `json:"super,omitempty"`
}

type MemberProfilePayload struct {
	Avatar                *string `json:"avatar,omitempty"`
	CanAccessClipboard    bool    `json:"can_access_clipboard"`
	CanConnect            bool    `json:"can_connect"`
	CanHost               bool    `json:"can_host"`
	CanLogin              bool    `json:"can_login"`
	CanSeeInactiveCursors bool    `json:"can_see_inactive_cursors"`
	CanShareMedia         bool    `json:"can_share_media"`
	CanWatch              bool    `json:"can_watch"`
	IsAdmin               bool    `json:"is_admin"`
	Name                  string  `json:"name"`
	Plugins               any     `json:"plugins"`
	SendsInactiveCursor   bool    `json:"sends_inactive_cursor"`
}

type OpenInAppInitPayload struct {
	Enabled bool `json:"enabled"`
}

type OpenInAppLinkPayload struct {
	Text string `json:"text"`
}

type PeerAudioPayload struct {
	Disabled bool `json:"disabled"`
}

type PeerAudioRequestPayload struct {
	Disabled *bool `json:"disabled,omitempty"`
}

type PeerVideoPayload struct {
	Auto     bool   `json:"auto"`
	Disabled bool   `json:"disabled"`
	Id       string `json:"id"`
}

type PeerVideoRequestPayload struct {
	Auto     *bool                  `json:"auto,omitempty"`
	Disabled *bool                  `json:"disabled,omitempty"`
	Selector *StreamSelectorPayload `json:"selector,omitempty"`
}

type ScreenSizePayload struct {
	Height int64 `json:"height"`
	Rate   int64 `json:"rate"`
	Width  int64 `json:"width"`
}

type ScreenSizeUpdatePayload struct {
	Height int64  `json:"height"`
	Id     string `json:"id"`
	Rate   int64  `json:"rate"`
	Width  int64  `json:"width"`
}

type SendBroadcastPayload struct {
	Body    any    `json:"body"`
	Sender  string `json:"sender"`
	Subject string `json:"subject"`
}

type SendUnicastPayload struct {
	Body     any    `json:"body"`
	Receiver string `json:"receiver"`
	Sender   string `json:"sender"`
	Subject  string `json:"subject"`
}

type SessionCursorsPayload struct {
	Cursors []CursorPayload `json:"cursors"`
	Id      string          `json:"id"`
}

type SessionDataPayload struct {
	Id      string               `json:"id"`
	Profile MemberProfilePayload `json:"profile"`
	State   SessionStatePayload  `json:"state"`
}

type SessionIDPayload struct {
	Id string `json:"id"`
}

type SessionProfileUpdatePayload struct {
	Avatar                *string `json:"avatar,omitempty"`
	CanAccessClipboard    bool    `json:"can_access_clipboard"`
	CanConnect            bool    `json:"can_connect"`
	CanHost               bool    `json:"can_host"`
	CanLogin              bool    `json:"can_login"`
	CanSeeInactiveCursors bool    `json:"can_see_inactive_cursors"`
	CanShareMedia         bool    `json:"can_share_media"`
	CanWatch              bool    `json:"can_watch"`
	Id                    string  `json:"id"`
	IsAdmin               bool    `json:"is_admin"`
	Name                  string  `json:"name"`
	Plugins               any     `json:"plugins"`
	SendsInactiveCursor   bool    `json:"sends_inactive_cursor"`
}

type SessionStatePayload struct {
	ConnectedSince    any  `json:"connected_since,omitempty"`
	IsConnected       bool `json:"is_connected"`
	IsWatching        bool `json:"is_watching"`
	NotConnectedSince any  `json:"not_connected_since,omitempty"`
	NotWatchingSince  any  `json:"not_watching_since,omitempty"`
	WatchingSince     any  `json:"watching_since,omitempty"`
}

type SessionStateUpdatePayload struct {
	ConnectedSince    any    `json:"connected_since,omitempty"`
	Id                string `json:"id"`
	IsConnected       bool   `json:"is_connected"`
	IsWatching        bool   `json:"is_watching"`
	NotConnectedSince any    `json:"not_connected_since,omitempty"`
	NotWatchingSince  any    `json:"not_watching_since,omitempty"`
	WatchingSince     any    `json:"watching_since,omitempty"`
}

type SettingsPayload struct {
	ControlLeaseTtl   int64 `json:"control_lease_ttl"`
	ControlProtection bool  `json:"control_protection"`
	HeartbeatInterval int64 `json:"heartbeat_interval"`
	ImplicitHosting   bool  `json:"implicit_hosting"`
	InactiveCursors   bool  `json:"inactive_cursors"`
	LockedControls    bool  `json:"locked_controls"`
	LockedLogins      bool  `json:"locked_logins"`
	MercifulReconnect bool  `json:"merciful_reconnect"`
	Plugins           any   `json:"plugins"`
	PrivateMode       bool  `json:"private_mode"`
}

type SignalCandidatePayload struct {
	Candidate        string `json:"candidate"`
	SdpMLineIndex    any    `json:"sdpMLineIndex,omitempty"`
	SdpMid           any    `json:"sdpMid,omitempty"`
	UsernameFragment any    `json:"usernameFragment,omitempty"`
}

type SignalDescriptionPayload struct {
	Sdp string `json:"sdp"`
}

type SignalProvidePayload struct {
	Audio      PeerAudioPayload   `json:"audio"`
	Iceservers []ICEServerPayload `json:"iceservers"`
	Sdp        string             `json:"sdp"`
	Video      PeerVideoPayload   `json:"video"`
}

type SignalRequestPayload struct {
	Audio       *PeerAudioRequestPayload `json:"audio,omitempty"`
	Video       *PeerVideoRequestPayload `json:"video,omitempty"`
	VideoCodecs *[]string                `json:"video_codecs,omitempty"`
}

type StreamSelectorPayload struct {
	Bitrate int64  `json:"bitrate"`
	Id      string `json:"id"`
	Type    string `json:"type"`
}

type SystemAdminPayload struct {
	BroadcastStatus BroadcastStatusPayload `json:"broadcast_status"`
}

type SystemDisconnectPayload struct {
	Message string `json:"message"`
}

type SystemInitPayload struct {
	ControlHost       ControlHostPayload            `json:"control_host"`
	ScreenSize        ScreenSizePayload             `json:"screen_size"`
	ScreencastEnabled bool                          `json:"screencast_enabled"`
	SessionId         string                        `json:"session_id"`
	Sessions          map[string]SessionDataPayload `json:"sessions"`
	Settings          SettingsPayload               `json:"settings"`
	TouchEvents       bool                          `json:"touch_events"`
	Webrtc            SystemWebRTCPayload           `json:"webrtc"`
}

type SystemLogPayload struct {
	Fields  map[string]any `json:"fields"`
	Level   string         `json:"level"`
	Message string         `json:"message"`
}

type SystemSettingsUpdatePayload struct {
	ControlLeaseTtl   int64  `json:"control_lease_ttl"`
	ControlProtection bool   `json:"control_protection"`
	HeartbeatInterval int64  `json:"heartbeat_interval"`
	Id                string `json:"id"`
	ImplicitHosting   bool   `json:"implicit_hosting"`
	InactiveCursors   bool   `json:"inactive_cursors"`
	LockedControls    bool   `json:"locked_controls"`
	LockedLogins      bool   `json:"locked_logins"`
	MercifulReconnect bool   `json:"merciful_reconnect"`
	Plugins           any    `json:"plugins"`
	PrivateMode       bool   `json:"private_mode"`
}

type SystemWebRTCPayload struct {
	Videos []string `json:"videos"`
}
